### ISSUE TITLE
Unsupported block-store URI scheme: "mem:-"

### ISSUE THREAD

**Issue by victorb** [greglook/blocks#22]
Following the examples from the README, something like this should be possible to create the store:

```clojure
(require '[blocks.store :as store])
(def store (block/->store "mem:-"))
```

But instead it throws the following error:

```
Syntax error (IllegalArgumentException) compiling at (form-init11663713394850559011.clj:1:12).
Unsupported block-store URI scheme: "mem:-"
```

Running `(store/parse-uri "mem:-")` returns `{:scheme "mem", :name "-"}` so seems to work fine on the surface at least.

**Comment by greglook** [comment]
Have you required the `blocks.store.memory` namespace? Each of the store namespaces extends the initialization multimethod.
https://github.com/greglook/blocks/blob/ded25dbc8005f37350dd364a12343e5150de956d/src/blocks/store/memory.clj#L102-L104

**Comment by greglook** [comment]
I realized this was missing from the README: https://github.com/greglook/blocks/commit/223bafe1b7bc7664c80b41d1fd10b2f690aa7575

**Comment by victorb** [comment]
Awesome, that was indeed what was missing for me. Thanks for the quick resolution!
