### ISSUE TITLE
puget dependency version update required for Clojure 1.12 compatibility

### ISSUE THREAD

**Issue by JarrodCTaylor** [greglook/blocks#24]
Blocks has a dependency on [mvxcvi/puget "1.3.1"]. This older version has a dependency on [fipp "0.6.23"], which uses the private `clojure.instant/thread-local-utc-date-format` that is [removed in Clojure 1.12](https://clojure.atlassian.net/browse/CLJ-2803) 

This is no longer an issue in [mvxcvi/puget "1.3.4"]

**Comment by greglook** [comment]
This dependency is in the `:dev` profile so it'd only be for local development; is this impacting your usage of the library? Either way, updated in 3a0a39a347817fab543960186d577635e6f75f6a.
